language: python
services:
  - docker
env:
  - ENV=ubuntu2004
  - ENV=centos8


before_install:  
  - sudo apt-get update
  - sudo apt-get -y install shunit2
script:
    - cd linux/test
    - PGVER=$PGVER ./docker-build.sh $ENV
    - ./test_services.sh
    - cd ..
    - ./autogenerate.sh
