language: python
services:
  - docker
env:
  - ENV=centos7_nginx PGVER=pg10
  - ENV=ubuntu1604_nginx PGVER=pg10
  - ENV=debian9_nginx PGVER=pg10
  - ENV=centos7_nginx PGVER=pg96
  - ENV=ubuntu1604_nginx PGVER=pg96
  - ENV=debian9_nginx PGVER=pg96
  - ENV=ubuntu1604_nginx JAVAVER=openjdk11
  - ENV=debian9_nginx JAVAVER=openjdk11
  - ENV=debian9_nginx JAVAVER=oracle11
  - ENV=ubuntu1604_nginx JAVAVER=oracle11
  - ENV=ubuntu1804_nginx JAVAVER=openjdk11
  - ENV=ubuntu1804_nginx
  - ENV=fedora30_nginx

before_install:  
  - sudo apt-get update
  - sudo apt-get -y install shunit2
script:
    - cd linux/test
    - PGVER=$PGVER ./docker-build.sh $ENV
    - ./test_services.sh
    - cd ..
    - ./autogenerate.sh
